#!/bin/bash
set -e
set -u

echo "checking for libstatgrab interface version"
echo "/* config.h generated by configure script */" >> config.h
echo "" >> config.h

mkdir -p tmp
fn=tmp/sg.c
echo "#include <statgrab.h>" > "$fn"
echo "int main() { sg_get_cpu_percents(); }" >> "$fn"
if ! gcc -o tmp/sg.o -c "$fn" > /dev/null 2>&1; then
    echo "libstatgrab 0.17 interface doesn't work, assuming 0.90"
    echo "#define LIBSTATGRAB_API_0_90" >> config.h
else
    echo "found libstatgrab 0.17 interface"
    echo "#define LIBSTATGRAB_API_0_17" >> config.h
fi
rm -rf tmp

